export const adminContentConfig = {
  services: {
    title: "Services",
    endpoint: "/services",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "shortDescription", label: "Short Description", type: "textarea", required: true },
      { name: "description", label: "Detailed Description", type: "textarea", required: true },
      {
        name: "icon",
        label: "Icon Name",
        type: "select",
        options: ["MonitorCog", "LineChart", "Users", "GraduationCap", "ShieldCheck", "Sparkles"],
      },
      { name: "image", label: "Image URL", type: "image" },
      { name: "highlights", label: "Highlights", type: "multiline-list" },
      { name: "process", label: "Delivery Process", type: "multiline-list" },
      { name: "industryFocus", label: "Industry Focus", type: "multiline-list" },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "seoTitle", label: "SEO Title", type: "text" },
      { name: "seoDescription", label: "SEO Description", type: "textarea" },
    ],
    previewFields: ["title", "shortDescription", "icon"],
  },
  blogs: {
    title: "Blogs",
    endpoint: "/blogs",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea", required: true },
      { name: "content", label: "Content", type: "richtext", required: true },
      { name: "coverImage", label: "Cover Image", type: "image" },
      { name: "author", label: "Author", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "tags", label: "Tags", type: "comma-list" },
      { name: "readTime", label: "Read Time", type: "text" },
      { name: "isFeatured", label: "Featured", type: "checkbox" },
      { name: "publishedAt", label: "Published Date", type: "date" },
      { name: "seoTitle", label: "SEO Title", type: "text" },
      { name: "seoDescription", label: "SEO Description", type: "textarea" },
    ],
    previewFields: ["title", "category", "author"],
  },
  jobs: {
    title: "Jobs",
    endpoint: "/jobs",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "type", label: "Employment Type", type: "text" },
      { name: "experience", label: "Experience", type: "text" },
      { name: "department", label: "Department", type: "text" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "responsibilities", label: "Responsibilities", type: "multiline-list" },
      { name: "qualifications", label: "Qualifications", type: "multiline-list" },
      { name: "isActive", label: "Active Listing", type: "checkbox" },
      { name: "seoTitle", label: "SEO Title", type: "text" },
      { name: "seoDescription", label: "SEO Description", type: "textarea" },
    ],
    previewFields: ["title", "location", "experience"],
  },
  "case-studies": {
    title: "Case Studies",
    endpoint: "/case-studies",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "client", label: "Client", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "challenge", label: "Challenge", type: "textarea", required: true },
      { name: "solution", label: "Solution", type: "textarea", required: true },
      { name: "outcome", label: "Outcome", type: "textarea", required: true },
      { name: "metrics", label: "Metrics", type: "metrics" },
      { name: "services", label: "Related Services", type: "comma-list" },
      { name: "tags", label: "Tags", type: "comma-list" },
      { name: "coverImage", label: "Cover Image", type: "image" },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "seoTitle", label: "SEO Title", type: "text" },
      { name: "seoDescription", label: "SEO Description", type: "textarea" },
    ],
    previewFields: ["title", "industry", "client"],
  },
};

